name: Publish

on:
  push:
    tags:
      - '*'
  release:
    types:
      - created
jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v2
      - name: Assembly
        run: sbt assembly

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/scala-2.13/TeamResults.jar
          tag: ${{ github.ref }}
          overwrite: true
        